version: '3.5'

networks:
  server:
    driver: bridge

  client:
    driver: bridge

  database:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24

services:
  server:
    restart: always
    build:
      context: server
      dockerfile: build/package/Dockerfile
    command: go run cmd/server/server.go
    networks:
      - server
    ports:
      - '8080:8080'
    volumes:
      - ./server/:/go/src/server

  client:
    restart: always
    build:
      context: client
      dockerfile: build/Dockerfile
    command: |
      sh -c "npm install && npm run dev"
    networks:
      - client
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/usr/src/client

  postgres:
    image: postgres
    restart: always
    environment:
      DB_NAME: neoacademy
      POSTGRES_USER: neoacademy
      POSTGRES_PASSWORD: neoacademy
    networks:
      database:
        ipv4_address: 10.10.10.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@neoacademy.dev
      PGADMIN_DEFAULT_PASSWORD: neoacademy
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    networks:
      database:
        ipv4_address: 10.10.10.4